schema:
 input:
 type: object
 properties:
 bucket_name:
 type: string
 description: "The name of the S3 bucket"
 aws_region:
 type: string
 description: "The AWS region to deploy in"
 default: "ap-south-1"